language:
    python
python:
    # Travis doesn't seem to support python 2.6 anymore?
    - "2.7"

    # Coveralls isn't compatible with python 3.0-3.4, so just don't bother.
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "nightly"
install:
    - pip install python-coveralls pytest-cov
    - pip install .
script: 
    - py.test . -vv --cov autoprop
after_success:
    - coveralls
